/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime=false` (hash: 4c8035ad6dff9e5fbc21f5422b8763b9)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "ProviderSchedulerDurableObject";
	}
	interface Env {
		CHISHA_DB: D1Database;
		RL_AGENT_CHAT: RateLimit;
		RL_AGENT_CHAT_ALL: RateLimit;
		RL_AMAP_PROXY: RateLimit;
		RL_GEOCODE: RateLimit;
		RL_AGENT_SESSION: RateLimit;
		ASSETS: Fetcher;
		AMAP_API_KEY: string;
		AMAP_JS_API_KEY: string;
		AMAP_SECURITY_CODE: string;
		SESSION_OWNER_SECRET: string;
		OPENAI_API_KEY: string;
		OPENAI_BASE_URL: string;
		OPENAI_MODEL: string;
		PROVIDER_SCHEDULER: DurableObjectNamespace<import("./worker").ProviderSchedulerDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
